development:
  adapter: postgresql
  encoding: utf8
  database: Portfolio_site_development
  pool: 5


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: Portfolio_site_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: Portfolio_site_production
  pool: 5


cucumber:
  <<: *TEST
